version: "3"

services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
